language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version  # print the version for logging
  # user api
  - docker build -t ms-user-api ./udagram-user-api
  - docker tag ms-user-api iaguest/ms-user-api:latest
  # feed api
  - docker build -t ms-feed-api ./udagram-feed-api
  - docker tag ms-feed-api iaguest/ms-feed-api:latest
  # reverse proxy
  - docker build -t ms-rev-proxy ./udagram-rev-proxy
  - docker tag ms-rev-proxy iaguest/ms-rev-proxy:latest
  # frontend
  - docker build -t ms-frontend ./udagram-frontend
  - docker tag ms-frontend iaguest/ms-frontend:latest

# Tasks to perform after the process is successful.
# Formatting the Docker username and password as below enables you
#to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push iaguest/ms-user-api
  - docker push iaguest/ms-feed-api
  - docker push iaguest/ms-rev-proxy
  - docker push iaguest/ms-frontend
  