apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-frontend
  name: ms-frontend-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/ms-frontend-svc
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    app: ms-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
