apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-feed-api
  labels:
    app: ms-feed-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-feed-api
  template:
    metadata:
      labels:
        app: ms-feed-api
    spec:
      containers:
      - name: ms-feed-api
        image: iaguest/ms-feed-api
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
