apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: ms-rev-proxy
  name: ms-rev-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-rev-proxy
  template:
    metadata:
      labels:
        app: ms-rev-proxy
        service: ms-rev-proxy
    spec:
      containers:
      - image: iaguest/ms-rev-proxy
        name: ms-rev-proxy
        imagePullPolicy: Always                
        ports:
        - containerPort: 8100
      restartPolicy: Always


