apiVersion: v1
kind: Service
metadata:
  labels:
    service: ms-rev-proxy
  name: ms-rev-proxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: ms-rev-proxy
